# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-4.10"

  jobs:

    pre_build:
      - ./docs/rtd/pre_build.sh
      - mkdir -p docs/build
      - doxygen Doxyfile
      - ./docs/plot.sh

  apt_packages:
    - graphviz

formats:
  - pdf
  - epub


conda:
  environment: docs/environment.yml

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true

formats: all
