# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-4.10"

  jobs:
    post_checkout:
      # Cancel building pull requests when there aren't changed in the docs directory or YAML file.
      # You can add any other files or directories that you'd like here as well,
      # like your docs requirements file, or other files that will change your docs build.
      #
      # If there are no changes (git diff exits with 0) we force the command to return with 183.
      # This is a special exit code on Read the Docs that will cancel the build immediately.
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- docs/ .readthedocs.yaml;
        then
          exit 183;
        fi
      - (git --no-pager log --pretty="tformat:%s -- %b" -1 | grep -viq "skip ci") || exit 183
    pre_build:
      - ./docs/rtd/pre_build.sh
      - ./scripts/doxygen.sh
      - ./docs/rtd/plot.sh
    post_build:
      - ./docs/rtd/post_build.sh

  apt_packages:
    - graphviz

formats:
  - pdf
  - epub

conda:
  environment: docs/environment.yml

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
