name: Backport
on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-18.04
    name: Backport
    steps:
      - name: Backport Bot
        if: contains( join(github.event.pull_request.labels.*.name), 'backport')
        uses: Gaurav0/backport@v1.0.24
        with:
          bot_username: PROJ-BOT
          bot_token: c1c49a5799d0a3a3885db8a4792880cbe509c1d6
          bot_token_key: b01bdebf64595ed77207019258316df1b05ff6ac
          github_token: ${{ secrets.GITHUB_TOKEN }}
