--- This file has been generated by scripts/build_db_equinor.py. DO NOT EDIT !

INSERT INTO "prime_meridian" VALUES('EQNR','8901','Greenwich',0.0,'EQNR','9102',0);
INSERT INTO "prime_meridian" VALUES('EQNR','8902','Lisbon',-9.0754862,'EQNR','9110',0);
INSERT INTO "prime_meridian" VALUES('EQNR','8903','Paris',2.5969213,'EQNR','9105',0);
INSERT INTO "prime_meridian" VALUES('EQNR','8904','Bogota',-74.04513,'EQNR','9110',0);
INSERT INTO "prime_meridian" VALUES('EQNR','8905','Madrid',-3.411455,'EQNR','9110',0);
INSERT INTO "prime_meridian" VALUES('EQNR','8906','Rome',12.27084,'EQNR','9110',0);
INSERT INTO "prime_meridian" VALUES('EQNR','8907','Bern',7.26225,'EQNR','9110',0);
INSERT INTO "prime_meridian" VALUES('EQNR','8908','Jakarta',106.482779,'EQNR','9110',0);
INSERT INTO "prime_meridian" VALUES('EQNR','8909','Ferro',-17.4,'EQNR','9110',0);
INSERT INTO "prime_meridian" VALUES('EQNR','8910','Brussels',4.220471,'EQNR','9110',0);
INSERT INTO "prime_meridian" VALUES('EQNR','8911','Stockholm',18.03298,'EQNR','9110',0);
INSERT INTO "prime_meridian" VALUES('EQNR','8912','Athens',23.4258815,'EQNR','9110',0);
INSERT INTO "prime_meridian" VALUES('EQNR','8913','Oslo',10.43225,'EQNR','9110',0);
INSERT INTO "prime_meridian" VALUES('EQNR','8914','Paris RGS',2.201395,'EQNR','9110',0);
