# $Id$
#
# NMAKE Makefile to build PROJ.4 on Windows
#
# This makefile.vc delegates making targets to src\makefile.vc
# so it's just a thin wrapper.
#
MAKE = nmake
RM = -del

default:    src_dir

src_dir:
	cd src
	$(MAKE) /f makefile.vc
	cd ..

clean:	
	cd src
	$(MAKE) /f makefile.vc clean
	$(RM) *.exe
	$(RM) *.ilk
	$(RM) *.manifest
	$(RM) *.pdb
	cd ..

