name: proj
channels:
  - conda-forge
dependencies:
  - descartes
  - doxygen < 1.8.17
  - geojson
  - matplotlib
  - shapely < 1.8
  - libcxx
  - libsqlite
  - sqlite
  - compilers
  - cmake
  - ninja
  - pip
  - pip:
    - breathe < 4.15
    - Jinja2 < 3.1
    - pybtex
    - sphinx < 3
    - sphinx-rtd-theme < 1.0
    - sphinxcontrib-bibtex
    - sphinxcontrib-spelling
