name: proj
channels:
  - conda-forge
dependencies:
  - descartes
  - geojson
  - matplotlib
  - shapely < 1.8
  - pip
  - pip:
    - Jinja2 < 3.1
    - pybtex
    - sphinx < 3
    - sphinx-rtd-theme < 1.0
    - sphinxcontrib-bibtex
