name: Emscripten

on:
  push:
      paths-ignore:
          - 'docs/**'
  pull_request:
      paths-ignore:
          - 'docs/**'


concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  emscripten:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Build docker
        run: docker build -t proj-emscripten-builder scripts/ci/emscripten/

      - name: Artifacts folder
        run: mkdir -p "$PWD"/wasm_out

      - name: Run docker build
        run: |
          docker run --user $(id -u):$(id -g) --rm \
            -e PROJ_GITHUB_SHA=${{ github.sha }} \
            -v "$PWD":/build/proj_src \
            -v "$PWD"/wasm_out:/build/install \
            proj-emscripten-builder

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: proj-js-wasm
          retention-days: 90
          path: wasm_out/projModule.*

      - name: Copy for tests
        run: |
          mkdir -p "$PWD"/out_node
          cp wasm_out/projModule.* out_node
          cp scripts/ci/emscripten/proj.ems.tests.js out_node

      - name: Run docker tests
        run: |
          docker run --user $(id -u):$(id -g) --rm \
            -v "$PWD"/out_node:/opt/node/tests \
            node:24-alpine \
            node /opt/node/tests/proj.ems.tests.js

      - name: Deploy ssh key (wasm_proj)
        if: ${{ github.event_name == 'push' && github.ref_name == 'master' && github.repository == 'OSGeo/PROJ' }}
        shell: bash -l {0}
        env:
          WASM_PROJ_DEPLOY_SSH_KEY: ${{ secrets.WASM_PROJ_DEPLOY_SSH_KEY }}   # zizmor: ignore[secrets-outside-env]
        run: |
          mkdir $HOME/.ssh && echo "${WASM_PROJ_DEPLOY_SSH_KEY}" > $HOME/.ssh/id_rsa
          chmod 700 $HOME/.ssh && chmod 600 $HOME/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> $HOME/.ssh/known_hosts
          eval `ssh-agent -s`
          ssh-add $HOME/.ssh/id_rsa

      - name: Deploy to wasm-proj/master pages
        if: ${{ github.event_name == 'push' && github.ref_name == 'master' && github.repository == 'OSGeo/PROJ' }}
        shell: bash -l {0}
        run: |
          set -x
          set -e
          git clone -b pages git@github.com:jjimenezshaw/wasm-proj.git wasm_proj_pages
          cp wasm_out/projModule.* wasm_proj_pages/master/wasm/
          cd wasm_proj_pages
          git config user.email "proj-master-updater@example.com"
          git config user.name "Automatic PROJ updater"
          git remote -v
          git rev-parse --abbrev-ref HEAD
          git add -A
          git commit -m "Update wasm with OSGeo/PROJ commit $GITHUB_SHA"
          git push -f origin pages
