name: Plots

on: [push, pull_request]

jobs:

  plots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          channels: conda-forge
          auto-update-conda: true
      - name: Setup
        shell: bash -l {0}
        run: |
            conda update -n base -c defaults conda
            conda install descartes shapely geopandas matplotlib
      - name: Setup
        shell: bash -l {0}
        working-directory: ./docs/plot
        run: |
            ./plot.sh

      - uses: actions/upload-artifact@v2
        with:
          name: Images
          path: docs/plot/images
